// <auto-generated />
using System;
using Da3m.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Da3m.Data.Migrations
{
    [DbContext(typeof(Da3mDbContext))]
    partial class Da3mDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Da3m.Domain.Center", b =>
                {
                    b.Property<int>("CenterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CenterId"));

                    b.Property<string>("CenterName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LocationText")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("CenterId")
                        .HasName("PK__Center__398FC7F720BEADF2");

                    b.ToTable("Center");
                });

            modelBuilder.Entity("Da3m.Domain.Doctor", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int?>("CenterId")
                        .HasColumnType("int");

                    b.Property<string>("HospitalName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDeletd")
                        .HasColumnType("bit");

                    b.Property<string>("LicenseNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Specialty")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("UserId")
                        .HasName("PK__Doctor__1788CC4C0D2FE729");

                    b.HasIndex("CenterId");

                    b.ToTable("Doctor");
                });

            modelBuilder.Entity("Da3m.Domain.Donation", b =>
                {
                    b.Property<int>("DonationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DonationId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("DonationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool>("IsDeletd")
                        .HasColumnType("bit");

                    b.Property<string>("Note")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("DonationId")
                        .HasName("PK__Donation__C5082EFBCF8F1113");

                    b.HasIndex("UserId");

                    b.ToTable("Donation");
                });

            modelBuilder.Entity("Da3m.Domain.DonorDetail", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int?>("DonatedDevicesCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<bool>("IsDeletd")
                        .HasColumnType("bit");

                    b.Property<string>("PreferredDonationType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("TotalDonatedAmount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.HasKey("UserId")
                        .HasName("PK__DonorDet__1788CC4C2B7CD459");

                    b.ToTable("DonorDetails");
                });

            modelBuilder.Entity("Da3m.Domain.ManufacturerDetail", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("CommercialRegister")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDeletd")
                        .HasColumnType("bit");

                    b.Property<string>("Website")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("UserId")
                        .HasName("PK__Manufact__1788CC4CAE650A16");

                    b.ToTable("ManufacturerDetails");
                });

            modelBuilder.Entity("Da3m.Domain.Match", b =>
                {
                    b.Property<int>("MatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MatchId"));

                    b.Property<int>("DeviceId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeletd")
                        .HasColumnType("bit");

                    b.Property<DateTime>("MatchDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<decimal>("MatchPercentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("MatchId")
                        .HasName("PK__Matches__4218C817991988DB");

                    b.HasIndex("DeviceId");

                    b.HasIndex("UserId");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("Da3m.Domain.Measurement", b =>
                {
                    b.Property<int>("MeasurementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MeasurementId"));

                    b.Property<decimal>("LengthCm")
                        .HasColumnType("decimal(6, 2)")
                        .HasColumnName("Length_cm");

                    b.Property<string>("LimbType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("MeasuredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Notes")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<decimal>("WidthCm")
                        .HasColumnType("decimal(6, 2)")
                        .HasColumnName("Width_cm");

                    b.HasKey("MeasurementId")
                        .HasName("PK__Measurem__85599FB8FDA0DA98");

                    b.HasIndex("UserId");

                    b.ToTable("Measurement");
                });

            modelBuilder.Entity("Da3m.Domain.PatientDetail", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("DisabilityType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("IsDeletd")
                        .HasColumnType("bit");

                    b.Property<string>("NationalId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserId")
                        .HasName("PK__PatientD__1788CC4CC395ED83");

                    b.ToTable("PatientDetails");
                });

            modelBuilder.Entity("Da3m.Domain.Prostheses", b =>
                {
                    b.Property<int>("DeviceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DeviceId"));

                    b.Property<DateTime>("AddedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Condition")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Direction")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsAvailable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeletd")
                        .HasColumnType("bit");

                    b.Property<decimal>("LengthCm")
                        .HasColumnType("decimal(6, 2)")
                        .HasColumnName("Length_cm");

                    b.Property<string>("LimbType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Material")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Note")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<decimal>("WidthCm")
                        .HasColumnType("decimal(6, 2)")
                        .HasColumnName("Width_cm");

                    b.HasKey("DeviceId")
                        .HasName("PK__Prosthes__49E12311B1B63DBA");

                    b.HasIndex("UserId");

                    b.ToTable("Prostheses");
                });

            modelBuilder.Entity("Da3m.Domain.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RoleId")
                        .HasName("PK__Role__8AFACE1AAC0A9BD0");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("Da3m.Domain.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId")
                        .HasName("PK__User__1788CC4C2B1B7071");

                    b.HasIndex("RoleId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("Da3m.Domain.VisitReport", b =>
                {
                    b.Property<int>("ReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReportId"));

                    b.Property<int>("CenterId")
                        .HasColumnType("int");

                    b.Property<string>("DoctorNotes")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsDeletd")
                        .HasColumnType("bit");

                    b.Property<int>("MatchId")
                        .HasColumnType("int");

                    b.Property<string>("PatientFeedback")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("ReportDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("ReportId")
                        .HasName("PK__VisitRep__D5BD480510351CF1");

                    b.HasIndex("CenterId");

                    b.HasIndex("MatchId");

                    b.ToTable("VisitReports");
                });

            modelBuilder.Entity("Da3m.Domain.Doctor", b =>
                {
                    b.HasOne("Da3m.Domain.Center", "Center")
                        .WithMany("Doctors")
                        .HasForeignKey("CenterId")
                        .HasConstraintName("FK_Doctor_Center");

                    b.HasOne("Da3m.Domain.User", "User")
                        .WithOne("Doctor")
                        .HasForeignKey("Da3m.Domain.Doctor", "UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Doctor_User");

                    b.Navigation("Center");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Da3m.Domain.Donation", b =>
                {
                    b.HasOne("Da3m.Domain.User", "User")
                        .WithMany("Donations")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Donation_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Da3m.Domain.DonorDetail", b =>
                {
                    b.HasOne("Da3m.Domain.User", "User")
                        .WithOne("DonorDetail")
                        .HasForeignKey("Da3m.Domain.DonorDetail", "UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Donor_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Da3m.Domain.ManufacturerDetail", b =>
                {
                    b.HasOne("Da3m.Domain.User", "User")
                        .WithOne("ManufacturerDetail")
                        .HasForeignKey("Da3m.Domain.ManufacturerDetail", "UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Manufacturer_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Da3m.Domain.Match", b =>
                {
                    b.HasOne("Da3m.Domain.Prostheses", "Device")
                        .WithMany("Matches")
                        .HasForeignKey("DeviceId")
                        .IsRequired()
                        .HasConstraintName("FK_Matches_Device");

                    b.HasOne("Da3m.Domain.User", "User")
                        .WithMany("Matches")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Matches_User");

                    b.Navigation("Device");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Da3m.Domain.Measurement", b =>
                {
                    b.HasOne("Da3m.Domain.User", "User")
                        .WithMany("Measurements")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Measurement_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Da3m.Domain.PatientDetail", b =>
                {
                    b.HasOne("Da3m.Domain.User", "User")
                        .WithOne("PatientDetail")
                        .HasForeignKey("Da3m.Domain.PatientDetail", "UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Patient_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Da3m.Domain.Prostheses", b =>
                {
                    b.HasOne("Da3m.Domain.User", "User")
                        .WithMany("Prostheses")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Prostheses_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Da3m.Domain.User", b =>
                {
                    b.HasOne("Da3m.Domain.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("FK_User_Role");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Da3m.Domain.VisitReport", b =>
                {
                    b.HasOne("Da3m.Domain.Center", "Center")
                        .WithMany("VisitReports")
                        .HasForeignKey("CenterId")
                        .IsRequired()
                        .HasConstraintName("FK_Report_Center");

                    b.HasOne("Da3m.Domain.Match", "Match")
                        .WithMany("VisitReports")
                        .HasForeignKey("MatchId")
                        .IsRequired()
                        .HasConstraintName("FK_Report_Match");

                    b.Navigation("Center");

                    b.Navigation("Match");
                });

            modelBuilder.Entity("Da3m.Domain.Center", b =>
                {
                    b.Navigation("Doctors");

                    b.Navigation("VisitReports");
                });

            modelBuilder.Entity("Da3m.Domain.Match", b =>
                {
                    b.Navigation("VisitReports");
                });

            modelBuilder.Entity("Da3m.Domain.Prostheses", b =>
                {
                    b.Navigation("Matches");
                });

            modelBuilder.Entity("Da3m.Domain.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Da3m.Domain.User", b =>
                {
                    b.Navigation("Doctor");

                    b.Navigation("Donations");

                    b.Navigation("DonorDetail");

                    b.Navigation("ManufacturerDetail");

                    b.Navigation("Matches");

                    b.Navigation("Measurements");

                    b.Navigation("PatientDetail");

                    b.Navigation("Prostheses");
                });
#pragma warning restore 612, 618
        }
    }
}
